# Conclusion

It can be concluded that females are more negatively affected by the pandemic than males in many aspects. The 70% of females in the global healthcare workforce have borne the brunt of the pandemic, as a much higher number of female health workers worldwide have been infected with COVID-19 than male health workers (female:male $\approx$ 3:1); namely, 75% of the infected health workers are females, which is greater than the percentage of 70% in the global healthcare workforce, so woman workers are also more likely than man workers to be infected with COVID-19. However, considerably less female health workers have died from the disease than male workers despite much more female workers were infected than male workers (female:male $\approx$ 2:3), which may be due to women's stronger immune system.

When it comes to physiology aspect, women are generally more advantageous. They are more likely to infected with covid-19 than men, but are less likely to die from the disease or be admitted to hospital. This may be explained by the fact that women has stronger immune systems that can better fight against virus. However, females' lower rate of getting hospitalized can possibly be indicating inequality in access to medical resources between men and women. This can be a topic for further research.

The pandemic has also exasperated the the pre-existing violence against women. In most countries we analyzed, the proportion of women that ever experienced a form of violence in lifetime are more than 50%, and the proportion since the pandemic is more than 25% for all the countries. Among all women, young women who are unemployed, living with children in rural area are the population affected most by violence during the pandemic. Here is a need to take measures to protect the vulnerable population from violence.

Overall, women's socioeconomic conditions are also more negatively affected by the pandemic than men's. Firstly, women are more negatively impacted by the pandemic in terms of economic activities, since they are more likely to lose their jobs and suffer from increased work hours after the pandemic, although they are also more likely to be covered by unemployment insurance and slightly less likely to suffer from income loss than men as a result of the pandemic. Secondly, women are more likely to be burdened with increased domestic and care work as a result of the pandemic, as they are more likely than men to be burdened with increased domestic activity, increased adultcare activity, and increased childcare activity, while being less likely than men to have received support from their spouse for domestic and care activities. Thirdly, women are more likely than men to face increased difficulty in accessing food, sanitary products, and medical care as a result of the pandemic.

One limitation of our project is that we are not able to explore the data in every dimension possible; for example, numbers of female and male health worker COVID-19 cases and deaths were only explored on the worldwide level and not by continents or countries. A main reason is that the data for some continents are of single digits and therefore is not meaningful for discovering trends across continents. A future direction could be to select some countries with large enough numbers that could produce meaningful results and explore trends across countries. Another limitation is that although the 5 datasets for the socioeconomic impacts of COVID-19 have been provided for 5 regions/continents and at least 52 countries by UN Women's RGA, they were mostly explored in the form of a combined dataset and therefore many trends across the regions/continents or countries were not spotted. Hence, another future direction could be exploring these trends across the regions/continents and/or countries.

From our project, it can be concluded that females are more negatively affected by the pandemic than males in many aspects. More women are in the healthcare workforce and women are also more likely to be infected with COVID-19 than men, but the media scarcely report or praise female workers' sacrifice and contribution, and some media even have portrayed female workers as unwilling to contribute. Women are more likely to suffer from increased violence, worsened socioeconomic conditions, and greater lack of access to resources than men, but far less than enough public attention or effort is directed to their disproportionate hardship caused by the pandemic. Therefore, awareness should be raised and more efforts should be made toward closing these various gender gaps that have been widened by the pandemic.